import {v4} from 'uuid'

const doctorsList = [
  {
    id: v4(),
    name: 'Dr. John Doe',
    rating: 4.5,
    expertise: 'Cardiology',
    experience: '10 years',
    language: 'English',
    videoFee: '1000',
    chatFee: '500',
    gender: 'Male',
  },
  {
    id: v4(),
    name: 'Dr. Jane Smith',
    rating: 4.8,
    expertise: 'Neurology',
    experience: '8 years',
    language: 'Hindi',
    videoFee: '1200',
    chatFee: '600',
    gender: 'Female',
  },
  {
    id: v4(),
    name: 'Dr. David Johnson',
    rating: 4.3,
    expertise: 'Orthopedics',
    experience: '12 years',
    language: 'English',
    videoFee: '1500',
    chatFee: '700',
    gender: 'Male',
  },
  {
    id: v4(),
    name: 'Dr. Sarah Lee',
    rating: 4.6,
    expertise: 'Pediatrics',
    experience: '9 years',
    language: 'Tamil',
    videoFee: '1100',
    chatFee: '550',
    gender: 'Female',
  },
  {
    id: v4(),
    name: 'Dr. Michael Brown',
    rating: 4.4,
    expertise: 'Cardiology',
    experience: '11 years',
    language: 'Hindi',
    videoFee: '1300',
    chatFee: '600',
    gender: 'Male',
  },
  {
    id: v4(),
    name: 'Dr. Emily Davis',
    rating: 4.7,
    expertise: 'Neurology',
    experience: '7 years',
    language: 'English',
    videoFee: '1400',
    chatFee: '650',
    gender: 'Female',
  },
  {
    id: v4(),
    name: 'Dr. James Wilson',
    rating: 4.5,
    expertise: 'Orthopedics',
    experience: '13 years',
    language: 'Hindi',
    videoFee: '1600',
    chatFee: '750',
    gender: 'Male',
  },
  {
    id: v4(),
    name: 'Dr. Olivia Rodriguez',
    rating: 4.6,
    expertise: 'Pediatrics',
    experience: '8 years',
    language: 'Tamil',
    videoFee: '1200',
    chatFee: '600',
    gender: 'Female',
  },
  {
    id: v4(),
    name: 'Dr. William Martinez',
    rating: 4.3,
    expertise: 'Cardiology',
    experience: '12 years',
    language: 'English',
    videoFee: '1500',
    chatFee: '700',
    gender: 'Male',
  },
  {
    id: v4(),
    name: 'Dr. Sophia Clark',
    rating: 4.8,
    expertise: 'Neurology',
    experience: '9 years',
    language: 'Hindi',
    videoFee: '1300',
    chatFee: '650',
    gender: 'Female',
  },
]

const DoctorsList = () => <h1>Hi</h1>

export default DoctorsList
